name: Saludo Personalizado Workflow

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: '¿Cuál es tu nombre?'
        required: true
        type: string
        default: 'Amigo'

jobs:
  saludo-personalizado:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Imprimir Saludo Personalizado
      run: echo "¡Hola ${{ inputs.nombre }}! Gracias por ejecutar este workflow"