name: Saludo Personalizado

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'Nombre a saludar'
        required: true
        default: 'Mundo'
        type: string
        
jobs:
  saludar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Saludar con nombre personalizado
      run: echo "Hola ${{ inputs.nombre }}!"
